export const PRODUCT_SEED_ITEMS = [
  {
    "categoryGroup": "공장제",
    "brand": "Rolex",
    "model": "Submariner",
    "subModel": "Submariner Variant 1",
    "reference": "126610LN",
    "factoryName": "Clean",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 2650000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Anchor_rolex_submariner_my_collection_of_rolex_watches.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/dc/BWG9_lume_on_a_Rolex_Submariner_Date_style_Steeldive_homage_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/98/C3_lume_on_a_Rolex_Submariner_date_style_Watchdives_WD680Q_homage_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/6c/Il_primo_Rolex_Submariner_del_1953.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Omega",
    "model": "Speedmaster Professional",
    "subModel": "Speedmaster Professional Variant 2",
    "reference": "310.30.42.50.01.002",
    "factoryName": "VSF",
    "versionName": "V4",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 2780000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/c/cd/Backside_%28caseback%29_of_an_Omega_Speedmaster_Professional_chronograph_watch_%28%22Moon_watch%22%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/d4/Detailed_view_from_rear_on_chronograph_pushers_and_folding_clasp_of_an_Omega_Speedmaster_Professional_wristwatch_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/2/20/Folding_clasp_of_an_Omega_Speedmaster_Professional_wristwatch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/2/27/OMEGA-Speedmaster-Professional-Front_%28cropped%29.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Patek Philippe",
    "model": "Nautilus",
    "subModel": "Nautilus Variant 3",
    "reference": "5711/1A-010",
    "factoryName": "3KF",
    "versionName": "V5",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 2910000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/d/d3/ITiffany%27s_Patek_Philippe_Watch_Collection_04.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/56/Patek_Philippe_Calatrava%2C_dress_watch_per_eccellenza.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/7f/Tiffany%27s_Patek_Philippe_Watch_Collection_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/41/Tiffany%27s_Patek_Philippe_Watch_Collection_02.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Audemars Piguet",
    "model": "Royal Oak",
    "subModel": "Royal Oak Variant 4",
    "reference": "15500ST.OO.1220ST.04",
    "factoryName": "ZF",
    "versionName": "V6",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3040000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/7c/Royal_Oak_Offshore_watch_by_Audemars_Piguet.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/5/57/Audemars_Piguet_dress_watch_in_oro_carica_manuale%2C_fine_anni_%2770.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/94/Ultimate_in_Rose_Gold_Wristwatches_RCWATCHES.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/7c/Royal_Oak_Offshore_watch_by_Audemars_Piguet.JPG"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Cartier",
    "model": "Santos de Cartier",
    "subModel": "Santos de Cartier Variant 5",
    "reference": "WSSA0029",
    "factoryName": "APS",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3170000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/79/Cartier_Santos_wristwatch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/19/Cartier_Panthere_lady%27s_2_tone_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/5b/SAKURAKO_-_This_Cartier_watch_is_very_hot%21_%286031624197%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/4b/Santos-Dumont_and_the_wristwatch.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "IWC",
    "model": "Pilot Mark XX",
    "subModel": "Pilot Mark XX Variant 6",
    "reference": "IW328201",
    "factoryName": "M+",
    "versionName": "V4",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3300000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/b/b6/Vintage_Elgin_National_Watch_Co._Vintage_Pocket_Watch%2C_17_Jewels%2C_Hexagon-Shaped_Case_Marked_Supreme_IWC_Co.%2C_Size_12s%2C_Circa_1921_%2810827675195%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Detail_of_IWC_GST_ref._3707_-_dial_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/0/02/IWC_GST_ref._3707_-_dial.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Detail_of_IWC_GST_ref._3707_-_dial_%28cropped%29.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Panerai",
    "model": "Luminor Marina",
    "subModel": "Luminor Marina Variant 7",
    "reference": "PAM01312",
    "factoryName": "C+",
    "versionName": "V5",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3430000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/4/40/Marina_Militare_1936_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/0/0a/Panerai_6152_1_homage_-_dial_%285413423203%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/40/Marina_Militare_1936_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/cc/U-BOAT_Watch_-_Flickr_-_jm3.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "TAG Heuer",
    "model": "Carrera",
    "subModel": "Carrera Variant 8",
    "reference": "CBS2210.FC6534",
    "factoryName": "BTF",
    "versionName": "V6",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3560000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/5/51/TAG_Heuer_Carrera_blue.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/51/TAG_Heuer_Carrera_blue.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/73/TAG_Heuer_Carrera_chronograph_CV2010_retusche_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/18/TAG_Heuer_Carrera_chronograph_CV2010_retusche.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Breitling",
    "model": "Navitimer B01",
    "subModel": "Navitimer B01 Variant 9",
    "reference": "AB0139211B1A1",
    "factoryName": "ARF",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3690000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/3/37/Breitling_Navitimer_Cosmonaute_chronograph_watch_%28detail_N.2%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/f7/Breitling_Navitimer_Cosmonaute_chronograph_watch_%28detail%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/2/20/Breitling_Navitimer_Cosmonaute_chronograph_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/78/Breitling_Navitimer_chronograph_watch_%28detail%29.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Hublot",
    "model": "Big Bang Unico",
    "subModel": "Big Bang Unico Variant 10",
    "reference": "441.NX.1171.RX",
    "factoryName": "TF",
    "versionName": "V4",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3820000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/79/HUBLOT_%26_De_Beers_on_Rbson_street_are_closing_temporarily_because_of_COVID-19_pandemic_%2849718844292%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a3/Hublot_Geneve.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/9d/Hublot_Imoca_01.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/c2/Hublot_Imoca_03.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Tudor",
    "model": "Black Bay 58",
    "subModel": "Black Bay 58 Variant 11",
    "reference": "M79030N-F11",
    "factoryName": "ZF",
    "versionName": "V4",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 3950000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tudor_Heritage_Chronograph_%289614173638%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Tudor_Heritage_Ranger_watch_%2827446117146%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tudor_Heritage_Chronograph_%289614173638%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Tudor_Heritage_Ranger_watch_%2827446117146%29.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Jaeger-LeCoultre",
    "model": "Reverso Classic",
    "subModel": "Reverso Classic Variant 12",
    "reference": "Q2548440-F12",
    "factoryName": "APS",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Leather Strap",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 4080000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/70/Jaeger-LeCoultre-Reverso.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/6a/Detailed_view_on_balance_and_rotor_of_Jaeger-LeCoultre_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Jaeger-LeCoultre_men%27s_dress_watch_ca._1950s.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/45/Balance_of_a_wristwatch_Jaeger-LeCoultre_Master_Eight_Days_Perpetual_Squelette.png"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Vacheron Constantin",
    "model": "Overseas",
    "subModel": "Overseas Variant 13",
    "reference": "4500V-Factory-13",
    "factoryName": "PPF",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 4210000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Vacheron_Constantin_Patrimony_gold_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/aa/Vacheron_Constantin_dress_watch%2C_fine_anni_Ottanta.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/Sigmund_Freud_Museum_Vienna%2C_Freud_pocket_watch_Vacheron_Constantin.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/91/Watch_MET_66022.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Breguet",
    "model": "Classique 5177",
    "subModel": "Classique 5177 Variant 14",
    "reference": "5177BB-Factory-14",
    "factoryName": "ZF",
    "versionName": "V2",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Leather Strap",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 4320000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/70/1785_Breguet_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/c6/Breguet_Type_XX_watch_A%C3%A9ronautique_navale-3972-IMG_6188.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/c/c1/Breguet_Type_XX_watch_A%C3%A9ronautique_navale-3972-IMG_6201.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/b/be/Breguet_Watch.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Blancpain",
    "model": "Fifty Fathoms",
    "subModel": "Fifty Fathoms Variant 15",
    "reference": "5015-Factory-15",
    "factoryName": "XF",
    "versionName": "V3",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Rubber Strap",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 4450000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/8/8b/Blancpain_MG_2605.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/7f/Blancpain_MG_2607.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/77/Blancpain_Tourbillon_con_otto_giorni_di_riserva_di_carica%2C_fine_anni_Ottanta.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/16/Blancpain_ref._6501_a_carica_manuale_con_calendario_completo%2C_fine_anni_Ottanta.jpg"
    ]
  },
  {
    "categoryGroup": "공장제",
    "brand": "Zenith",
    "model": "Chronomaster El Primero",
    "subModel": "Chronomaster El Primero Variant 16",
    "reference": "03.3100-Factory-16",
    "factoryName": "OMF",
    "versionName": "V4",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "하이엔드 외관 마감, 데일리 착용 세팅",
    "price": 4580000,
    "shippingPeriod": "7~14일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/10/Chronograph_sub-dials_of_watch_Zenith_El_Primero.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/51/Detail_of_Zenith_El_Primero_chronograph_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1d/Middle_part_of_Zenith_El_Primero_chronograph_watch_-_%E3%82%A8%E3%83%AB%E3%83%BB%E3%83%97%E3%83%AA%E3%83%A1%E3%83%AD36000VpH.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/One_of_three_sub-dials_of_chronograph_watch_Zenith_El_Primero_36000_VpH_-_Tribute_to_Charles_Vermot.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Rolex",
    "model": "Datejust 41",
    "subModel": "Datejust 41 Variant 1",
    "reference": "126334-0020",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3150000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/f/f4/Rolex_watch_ladies_Datejust_1987.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Anchor_rolex_submariner_my_collection_of_rolex_watches.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/dc/BWG9_lume_on_a_Rolex_Submariner_Date_style_Steeldive_homage_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/98/C3_lume_on_a_Rolex_Submariner_date_style_Watchdives_WD680Q_homage_watch.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Rolex",
    "model": "GMT-Master II Batman",
    "subModel": "GMT-Master II Batman Variant 2",
    "reference": "126710BLNR-0002",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3270000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/3/3e/Rolex_GMT_Master_II_116710BLNR_Batman.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/cc/Watch_hands_of_Rolex_GMT_Master_II_116710BLNR_Batman_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/17/Rolex_GMT_Master_II_%284657617812%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/6c/Rolex_GMT_Master_II_Pepsi.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Rolex",
    "model": "Cosmograph Daytona",
    "subModel": "Cosmograph Daytona Variant 3",
    "reference": "116500LN-0001",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3390000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/1d/Rolex_Cosmograph_Daytona.png",
      "https://upload.wikimedia.org/wikipedia/commons/4/44/Detailed_view_of_Rolex_Daytona_chronograph_watch_and_watchstrap.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/67/RolexDaytona.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1b/Anchor_rolex_submariner_my_collection_of_rolex_watches.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Omega",
    "model": "Seamaster Diver 300M",
    "subModel": "Seamaster Diver 300M Variant 4",
    "reference": "210.30.42.20.03.001",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3510000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/3/34/Watch_crown_and_one_of_the_chronograph_push-buttons_on_watch_Omega_Seamaster_Diver_chronograph.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/b/b6/DOMINGO_DIVERS%C3%83O_GM-OMEGA_OMEGA_OMEGA_-_19.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/8/80/DOMINGO_DIVERS%C3%83O_GM-OMEGA_OMEGA_OMEGA_-_26.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/8/86/Detailed_view_on_Omega_Seamaster_chronograph_watch_%28300_meters_water_resist%29.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Tudor",
    "model": "Black Bay 58",
    "subModel": "Black Bay 58 Variant 5",
    "reference": "M79030N-0001",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3630000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tudor_Heritage_Chronograph_%289614173638%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tudor_Heritage_Chronograph_%289614173638%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/8/8e/Tudor_Heritage_Chronograph_%289614173638%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Tudor_Heritage_Ranger_watch_%2827446117146%29.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Jaeger-LeCoultre",
    "model": "Reverso Classic",
    "subModel": "Reverso Classic Variant 6",
    "reference": "Q2548440",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3750000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/70/Jaeger-LeCoultre-Reverso.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/45/Balance_of_a_wristwatch_Jaeger-LeCoultre_Master_Eight_Days_Perpetual_Squelette.png",
      "https://upload.wikimedia.org/wikipedia/commons/6/6a/Detailed_view_on_balance_and_rotor_of_Jaeger-LeCoultre_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/35/Jaeger-LeCoultre_men%27s_dress_watch_ca._1950s.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Vacheron Constantin",
    "model": "Overseas",
    "subModel": "Overseas Variant 7",
    "reference": "4500V/110A-B128",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3870000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/6/69/Vacheron_Constantin_Patrimony_gold_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/aa/Vacheron_Constantin_dress_watch%2C_fine_anni_Ottanta.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/Sigmund_Freud_Museum_Vienna%2C_Freud_pocket_watch_Vacheron_Constantin.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/9/91/Watch_MET_66022.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Breguet",
    "model": "Classique 5177",
    "subModel": "Classique 5177 Variant 8",
    "reference": "5177BB/29/9V6",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 3990000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/70/1785_Breguet_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/c6/Breguet_Type_XX_watch_A%C3%A9ronautique_navale-3972-IMG_6188.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/c/c1/Breguet_Type_XX_watch_A%C3%A9ronautique_navale-3972-IMG_6201.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/b/be/Breguet_Watch.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Blancpain",
    "model": "Fifty Fathoms",
    "subModel": "Fifty Fathoms Variant 9",
    "reference": "5015-1130-52B",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 4110000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/8/8b/Blancpain_MG_2605.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/7f/Blancpain_MG_2607.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/77/Blancpain_Tourbillon_con_otto_giorni_di_riserva_di_carica%2C_fine_anni_Ottanta.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/16/Blancpain_ref._6501_a_carica_manuale_con_calendario_completo%2C_fine_anni_Ottanta.jpg"
    ]
  },
  {
    "categoryGroup": "젠파츠",
    "brand": "Zenith",
    "model": "Chronomaster El Primero",
    "subModel": "Chronomaster El Primero Variant 10",
    "reference": "03.3200.3600/69.M3200",
    "factoryName": "Custom Hybrid",
    "versionName": "GEN-PARTS",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "젠 파츠 혼합 커스텀, 디테일 보강",
    "price": 4230000,
    "shippingPeriod": "3~5주",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/10/Chronograph_sub-dials_of_watch_Zenith_El_Primero.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/51/Detail_of_Zenith_El_Primero_chronograph_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1d/Middle_part_of_Zenith_El_Primero_chronograph_watch_-_%E3%82%A8%E3%83%AB%E3%83%BB%E3%83%97%E3%83%AA%E3%83%A1%E3%83%AD36000VpH.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/One_of_three_sub-dials_of_chronograph_watch_Zenith_El_Primero_36000_VpH_-_Tribute_to_Charles_Vermot.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Seiko",
    "model": "5 Sports",
    "subModel": "5 Sports Variant 1",
    "reference": "SRPD55K1",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 1750000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/f/f7/Black_Seiko_watch_close-up_%28detail%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/a/a3/Black_Seiko_watch_close-up.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/74/Dial_detail_of_a_Seiko_Speed-Timer_Chronograph_Automatic_6138-0040_%28%22Bullhead%22%29%2C_1976.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/18/Minute_hands_and_date_of_Seiko_chronograph_watch_%28detail%29.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Grand Seiko",
    "model": "Heritage Snowflake",
    "subModel": "Heritage Snowflake Variant 2",
    "reference": "SBGA211",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 1840000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/7/7d/Grand_Seiko_Automatic_Hi-Beat.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/0/0b/Grand_Seiko_Caliber_9S65_Automatic.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/3/31/Grand_Seiko_SBGR051_sideview.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/0/09/Grand_Seiko_SBGW231_sideview.JPG"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Longines",
    "model": "HydroConquest",
    "subModel": "HydroConquest Variant 3",
    "reference": "L3.781.4.96.6",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 1930000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/a/ad/Longines_183_pocket_watch_Oldest_Longines.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/4/4c/Longines_4_Grand_Prix_pocket_watch_-_clockwork_visible_-_enhanced_resolution_DSF3402-PSMS.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/5/5b/Longines_Golden_Watch.png",
      "https://upload.wikimedia.org/wikipedia/commons/a/a2/Longines_dress_watch_per_donna%2C_anni_%2760.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Oris",
    "model": "Aquis Date",
    "subModel": "Aquis Date Variant 4",
    "reference": "01 733 7730 4155-07 8 24 05PEB",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2020000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/9/9e/Detailed_view_on_chronograph_pushers_and_crown_of_Oris_ProDiver_Chronograph_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/7/7e/ORIS_ProDiver_Chronograph_%28cropped_and_turned_90_degrees%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/65/ORIS_ProDiver_Chronograph.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Oris_Divers_Sixtyfive.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Bell & Ross",
    "model": "BR 03",
    "subModel": "BR 03 Variant 5",
    "reference": "BR03A-BL-ST/SRB",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2110000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/1e/BellandRoss_Watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/1/1c/Parents_and_fans_watch_kids_playing_%2851726939044%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/fa/Ship%27s_Bell%2C_HMS_Bangor_-_geograph.org.uk_-_842963.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/b/b3/Michel_Vaillant_-_Nouvelle_saison%2C_tome_8_-_13_jours.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Nomos",
    "model": "Tangente",
    "subModel": "Tangente Variant 6",
    "reference": "139",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "40mm",
    "dialColor": "White",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2200000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/2/29/Nomos_Glash%C3%BCtte_Tangente_neomatik_41_Update.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/cc/Nomos_Tangente_neomatik_41_Update%2C_Ref._180%2C_DUW_6101_--_2023_--_0012X.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/6/65/Nomos_Tangente_neomatik_41_Update%2C_Ref._180%2C_DUW_6101_--_2023_--_0013X.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/e/e7/Nomos_Tangente_neomatik_41_Update%2C_Ref._180%2C_DUW_6101_--_2024_--_0149-51X.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Baume & Mercier",
    "model": "Riviera",
    "subModel": "Riviera Variant 7",
    "reference": "10616",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "41mm",
    "dialColor": "Green",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2290000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/1/12/Baume_%26_Mercier_Classima_18k_mens_quartz_watch.png",
      "https://upload.wikimedia.org/wikipedia/commons/3/37/Baume_et_Mercier_Classima_10324_Watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/3/38/Baume_et_Mercier_Clifton_Club_Shelby_Cobra_10344_watch.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/d8/Baume_et_Mercier_Petite_Promesse_10289_watch.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Frederique Constant",
    "model": "Classics Index",
    "subModel": "Classics Index Variant 8",
    "reference": "FC-303MC5B6",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "42mm",
    "dialColor": "Silver",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2380000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/d/d2/Frederique_Constant_watch.png",
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Frederique_Constant_Khanburgedei.png",
      "https://upload.wikimedia.org/wikipedia/commons/d/d2/Frederique_Constant_watch.png",
      "https://upload.wikimedia.org/wikipedia/commons/3/39/Frederique_Constant_Khanburgedei.png"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Citizen",
    "model": "Promaster Diver",
    "subModel": "Promaster Diver Variant 9",
    "reference": "BN0150-28E",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "43mm",
    "dialColor": "Black",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2470000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/b/bc/Citizen_Hyper_Aqualand_Diver%27s_Promaster_MA9004-21E%2C_digital_quartz_diving_watch_with_depth_gauge_%28cropped%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/b/bb/Citizen_Hyper_Aqualand_Diver%27s_Promaster_MA9004-21E%2C_digital_quartz_diving_watch_with_depth_gauge.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/c/ce/Citizen_Promaster_Automatic_NY0040-09EE_Diver_200_m.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/d/d3/Citizen_Promaster_Eco-Drive_AP0440-14F_Diver%27s_200_m_%28edited%2C_cropped_to_casing%29.jpg"
    ]
  },
  {
    "categoryGroup": "현지중고",
    "brand": "Hamilton",
    "model": "Khaki Field Auto",
    "subModel": "Khaki Field Auto Variant 10",
    "reference": "H70455533",
    "factoryName": "Local Stock",
    "versionName": "Used A~B+",
    "movement": "Automatic",
    "caseSize": "39mm",
    "dialColor": "Blue",
    "caseMaterial": "Stainless Steel",
    "strapMaterial": "Steel Bracelet",
    "features": "현지 매입 중고, 실물 컨디션 기준 등록",
    "price": 2560000,
    "shippingPeriod": "2~5일",
    "images": [
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Hamilton_Khaki_Field.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/e/e4/Hamilton_Khaki_X-Patrol%2C_automatic_chronograph_watch_with_movement_based_on_Valjoux_7750.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/e/e2/Back_view_of_the_model_22_ships_chronometer_hamilton_watch_company.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/f/fe/Hamilton_Khaki_Field.jpg"
    ]
  }
];
